title:  "Raphael Reitzig"
subtitle: "Thoughts of a computer scientist, teacher, programmer and LaTeXer."
author: "Raphael Reitzig"
description: "Computer scientist. Teacher. Programmer. LaTeXer."
email: reitzig@cs.uni-kl.de

gems: ['jekyll/scholar']
exclude:    [Gemfile, Gemfile.lock, run, build]
timezone:   "Europe/Berlin"
encoding:   "utf-8"
url: "http://reitzig.github.io"

permalink: /ramblings/:year/:title
mathjax-options: "displayAlign: \"left\", displayIndent: \"2em\", positionToHash: true"

markdown: kramdown
kramdown:
    syntax_highlighter: rouge
#    syntax_highlighter_opts: 
#        line_numbers: true

defaults:
  -
    scope:
      path:   ""
      type:   "pages"
    values:
      layout:   "page"
      mathjax-version:  "TeX-AMS_HTML"
  -
    scope:
      path:   ""
      type:   "posts"
    values:
      layout:   "post"
      mathjax-version:  "TeX-AMS_HTML-full"
      
scholar:
  style:  harvard1
  locale: en

  bibliography: publications.bib
  bibliography_template: "{{reference}}"

  details_dir:    publications
  details_layout: bib_details.html
  details_link:   Details
