title:  "Raphael Reitzig"
subtitle: "Thoughts of a computer scientist, teacher, programmer and LaTeXer."
author: "Raphael Reitzig"
description: "Computer scientist. Teacher. Programmer. LaTeXer."
email: reitzig[at]cs.uni-kl.de

gems: ['jekyll/scholar']
exclude:    [Gemfile, Gemfile.lock, run, build]
timezone:   "Europe/Berlin"
encoding:   "utf-8"
url: "http://reitzig.github.io"

permalink: /ramblings/:year/:title
mathjax-options: "displayAlign: \"left\", displayIndent: \"2em\", positionToHash: true"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  math_engine_opts:
    preview: true
  syntax_highlighter_opts:      
    block: 
      line_numbers: true

defaults:
  -
    scope:
      path:   ""
      type:   "pages"
    values:
      layout:   "page"
      mathjax-version:  "TeX-AMS_HTML"
      comments: false
  -
    scope:
      path:   ""
      type:   "posts"
    values:
      layout:   "post"
      mathjax-version:  "TeX-AMS_HTML-full"
      comments: true
      
scholar:
  style: _includes/structured-refs-web.csl
  locale: en

  bibliography: publications.bib
  bibliography_template: "{{reference}}"

  details_dir:    publications
  details_layout: bib_details.html
  details_link:   Details
  
tikz:
  format: svg
  dir: assets/tikz
  
disqus:
  shortname: 'raphaels-ramblings'
  enable: true
  
pgp:
  target: 'assets/signatures'
  key-id: '4F0B50B9'
  key-url: 'http://pgp.mit.edu:11371/pks/lookup?op=get&search=0x12F79CC14F0B50B9'
  css: '/css/tufte.css'
